language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jeandet
  password:
    secure: Pt5zm7BuBoQnG+kt2qb+bJ/Xt0xYydZPUIvJHaHWADNt5lKv4c3Y8xOHxFltLKO0TanBtGe/jjjBdU0hG2i/qrQXasVIU6/O2/sXBy3fpgNjt3JB3s0UW3t9mfie0jvYyeJCtrK0piqWJWSE5Y8jbXyDsnPZA7J20AgF0LsgxwpOoidTGE1AQWCnfJNeHj2cawVUyykzy3o2cH+FmKLhgpt4cjShJqRWGPdq4hFAzOpACNOlS8Ok0XzIioV288fPZmJN2HcIrMvGSWHZjvKe5vhAOVZGPJIbYVp5FazB28qY+YLsFe4B//Xo88vvwxxXZh4RDxRzBXQi2F0ta1iiIMPmXDLBnpDMR2I1a6WNX8ZpQZpsxITMvAFQ9ywZHeIZzjKadpGJPnN8Q1KOKJgssTX4rWfTyqITGURQBaql0v6yFppWRKh2U1btT3s3G6KbBtGWyaTYCyleZctIrSm2LkHBnCtQblS99imSWCcKzop4nhtb/aAU44Dc42ofs5mLl3B2BQc8VRCHoMvnBU3gZHXeMht8m98LutsWhwfm9mkJ1qEGqu/XK2sv+a1bN5mSNlTk4FH5sKbkJkAOdcnYvPQRve5GqhthL7KYC7IJqQaxQ4GPbw/NW/ivLUZhOAt5tgZalUwBqo5RD+raweXToI2L83nVEGlJo7RW6IT4zWM=
  on:
    tags: true
    repo: LaboratoryOfPlasmaPhysics/fart
    python: 3.6
